server:
  port: 8080
spring:
  boot:
    admin:
      url: http://nw-boot-admin:8080
      client:
        name: <%= dasherizedBaseName %>
        prefer-ip: true
management:
  security:
    enabled: false
